# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "green" # select quick color schemes: "beige", "blue", "brown", "green_light", "green", "orange", "purple", "red", "yellow_light", "yellow". If empty colors taken from _sass/ryancv/settings.scss

### Header
header:
  logo:
    image: "assets/img/logo.png"
    text: "Maicon Heck"
    alt: "Maicon Heck"

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Video"
      slug: "f-video"

    - name: "Music"
      slug: "f-music"

    - name: "Links"
      slug: "f-link"

    - name: "Image"
      slug: "f-image"

    - name: "Gallery"
      slug: "f-gallery"

    - name: "Content"
      slug: "f-content"
